pool:
  name: Azure Pipelines

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - BlazorDemo
    exclude:
    - BlazorDemo/azure-deployments

variables:
  BuildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore Web'
    inputs:
      command: restore
      projects: '**/BlazorDemo.Web.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Restore API'
    inputs:
      command: restore
      projects: '**/BlazorDemo.API.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build Web'
    inputs:
      projects: '**/BlazorDemo.Web.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Build API'
    inputs:
      projects: '**/BlazorDemo.API.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: PowerShell@2
    displayName: 'Delete Config'
    inputs:
      pwsh: true
      targetType: 'inline'
      script: |
        $destination = "BlazorDemo/BlazorDemo.Web/wwwroot/appsettings.json"
        Remove-Item -Path $destination -Force

  - task: DotNetCoreCLI@2
    displayName: 'Publish Web'
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/BlazorDemo.Web.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

  - task: DotNetCoreCLI@2
    displayName: 'Publish API'
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/BlazorDemo.API.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

  - task: CopyFiles@2
    displayName: 'Copy Bicep to Artifacts'
    inputs:
      SourceFolder: 'BlazorDemo/azure-deployments'
      Contents: '**/*'
      TargetFolder: '$(build.artifactstagingdirectory)/azure-deployments'


  - task: CopyFiles@2
    displayName: 'Copy Environment App Settings'
    inputs:
      SourceFolder: 'BlazorDemo/BlazorDemo.Web'
      Contents: 'appsettings.*.json'
      TargetFolder: '$(build.artifactstagingdirectory)/web-settings'
      
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(build.artifactstagingdirectory)'
      artifact: 'drop'
      publishLocation: 'pipeline'